/* For JavaDB/Derby */

DROP TABLE TUTORCOURSE;
DROP TABLE STUDENTCOURSE;
DROP TABLE SESSIONS;
DROP TABLE TUTOR;
DROP TABLE COURSE;
DROP TABLE EXPERIENCE;
DROP TABLE STUDENT;


CREATE TABLE COURSE (
	COURSECODE VARCHAR(7) NOT NULL, 
	COURSENAME VARCHAR(45) NOT NULL, 
	COURSEDESCRIPTION CLOB NOT NULL, 
	PRIMARY KEY (COURSECODE)
)	;

CREATE TABLE EXPERIENCE (
	EXPERIENCEID INT NOT NULL, 
	DESCRIPTION CLOB NOT NULL, 
	PRIMARY KEY (EXPERIENCEID)
)	;

CREATE TABLE SESSIONS (
	DATEKEY DATE NOT NULL, 
	TIMEKEY TIME NOT NULL, 
	STUDENTLASTNAME VARCHAR(45) NOT NULL, 
	SESSIONSTATUS INT NOT NULL, 
	SESSIONTOPIC CLOB NOT NULL, 
	PRIMARY KEY (DATEKEY, TIMEKEY)
)	;

CREATE TABLE STUDENT (
	STUDENTID INT NOT NULL, 
	LASTNAME VARCHAR(45) NOT NULL, 
	FIRSTNAME VARCHAR(45) NOT NULL, 
	EMAIL VARCHAR(45), 
        PHONENUMBER VARCHAR(45), 
	PRIMARY KEY (STUDENTID)
)	;

CREATE TABLE TUTOR (
	TUTORID INT NOT NULL, 
	LASTNAME VARCHAR(45) NOT NULL, 
	FIRSTNAME VARCHAR(45) NOT NULL, 
	EMAIL VARCHAR(45), 
	PHONENUMBER VARCHAR(15), 
	STATUS VARCHAR(45) NOT NULL, 
	EXPERIENCE_EXPERIENCEID INT NOT NULL, 
	PRIMARY KEY (TUTORID),
        FOREIGN KEY (EXPERIENCE_EXPERIENCEID) REFERENCES EXPERIENCE(EXPERIENCEID)
)	;

CREATE TABLE TUTORCOURSE (
   	TUTOR_TUTORID INT NOT NULL,
	COURSE_COURSECODE VARCHAR(7) NOT NULL,
   FOREIGN KEY (TUTOR_TUTORID) REFERENCES TUTOR(TUTORID),
   FOREIGN KEY (COURSE_COURSECODE) REFERENCES COURSE(COURSECODE)
)            ;

CREATE TABLE STUDENTCOURSE (
   	STUDENT_STUDENTID INT NOT NULL,
	COURSE_COURSECODE VARCHAR(7) NOT NULL,
   FOREIGN KEY (STUDENT_STUDENTID) REFERENCES STUDENT(STUDENTID),
   FOREIGN KEY (COURSE_COURSECODE) REFERENCES COURSE(COURSECODE)
)	;


